### ISSUE TITLE
SOLVED: No signal when Capsense module used (Forgotten Global Interrupt Enable)

### ISSUE THREAD

**Issue by akudoma** [PolyVinalDistillate/PSoC_DMA_NeoPixel#1]
Hello,

I want to start by thanking you for sharing this library. It has been hugely helpful! Also, I realize this is a long-shot given the repo activity in the last year but I am pretty stuck. 

Everything works beautifully, but if I add a CapSense module to the project and call the Start() method on it, all output from Dout disappears. I have it scoped and it is repeatable. I have dug down into the component and all the code and can't seem to find the conflict. 

For reference I am using a PSOC 5LP (CY8C5868AXI-LP035 on a CY8CKIT-050 dev board).

Any insights would be wonderful. I am very willing to test, contribute, and share the resulting changes back when done.

**Comment by PolyVinalDistillate** [comment]
Hello,
I can't remember my github login at the moment, and it's locked me out! I've definitely used this component with capsense before, as I had a system set up with R/G/B sliders and 3 selector buttons. Odd that you're having problems.. I wonder if your capsense component is chainging the clock configureation, or if it upsets the DMA...
I implemented my system with the CY8C5888, but I think I still have the CY8CKIT-050 kicking about from when I first discovered the PSoC. I could have a quick look at your project if you can find a platform to upload it to and provide a link for download. I'm guessing you know how to create a workspace bundle? (file->Create Workspace Bundle, then select minimal).
Nick.

**Comment by akudoma** [comment]
Hi Nick,Awesome, thank you for getting back to me!I will send my project as soon as I can get back home tonight.It gives me hope that you have used it before with the capsense module.After posting I realized I had increased the buffer size to include another byte for the white register some time ago. I am using RGBW LEDs. While it works fine on it's own, there is a good chance that my change was not done correctly and is the cause of the problems.I will also test tonight using the original.I can also test on one of the $10 5LP prototype boards now. I will give that a shot as well.Thank you again for replying, I really appreciate it!Very Respectfully,Jason

**Comment by PolyVinalDistillate** [comment]
ooo - didn't realise they'd brought out RGBW versions! I've had a quick look at the datasheet and if my memory serves correctly, it looks like the timing characteristics are basically the same. I'll keep an eye out for your updates : )

**Comment by akudoma** [comment]
Hi Nick,Yeah! The RGBW LEDs are pretty awesome. Same timing, they just have an extra byte at the top of the register for the white setting!Ok, I bundled some code and shared it here: https://www.dropbox.com/sh/urv42ww9r35269y/AAB3VM4mbfvSD27ljl2pz0faa?dl=0The NeoPixel archive is basically your demo code but with a capsense module added. It works great untill I call the CapSense_Start() function. Then the Dout signal flat-lines and nothing is clocked out.The ToShareTest archive is my modification to drive the RGBW chips. Again, seems to work fine until I call the start function for the Capsense. Please excuse the mess of a project, it is very much in experimental mode.Right now I am testing with one of these:https://www.adafruit.com/product/2860I would be more than happy to send you one as a thank you for your time and help if you are interested.Very Respectfully,Jason

**Comment by PolyVinalDistillate** [comment]
I've had a look at the files you sent. Your "ToShareTest" is a project workspace only with no code so I can't say much about that, but for the NeoPixel_Original where you run CapSense_Start(); I have found the problem. You'll kick yourself when I tell you : D

You need to run CyGlobalIntEnable; before CapSense_Start();! My base project doesn't include enabling of interrupts because it only uses the DMA controller to transfer pixel data.

Another change I made before I realised the actual problem was to specify the NeoPixel clock as 12.75 MHz instead of 12.8, because your clock solver indicates that the *actual* clock speed becomes 12.75 MHz

I suspect that your modification to the library to support 32 BPP will be absolutely fine.

`    
    //Start the NeoPixel component (16 pix, User array, 12.8 MHz base clock)

    NP_Start(16, pPixelArray, 12.75);

    CyGlobalIntEnable; <---!

    CapSense_Start();
`

No need to send me anything, though the offer is appreciated : ) I've got an outrageous amount of stuff knocking about already from the 70's through to the present! Yup - some of my junk is over 10 years older than I am!!

**Comment by akudoma** [comment]
Hi Nick,Oh my! I can't believe I forgot that. Wow. I had two different projects working and started merging them, I must have missed the line. I certainly didn't expect that behavior. Thank you!I'm not sure why the archive didn't have the code, sorry. I cleaned up the project to share, but below is a link to what should be the uncleaned up project folder if you are interested. I am on my phone at the moment so I will have to try archiving again later if you like.https://www.dropbox.com/sh/ugih4yrvu5ra3sd/AADyyYTLn58I2atEopaq6TDma?dl=0Thank you so much and I am sorry to bother you for something so simple. I will update the comment on github for you if you are still locked out to clarify it was my error.If you change your mind about the neopixle board just let me know. It sounds like you and I are about the same age and in the same boat when it comes to collecting parts and gadget.Thank you again for the help!Very Respectfully,Jason

**Comment by PolyVinalDistillate** [comment]
I regained access to GitHub yesterday : ) No idea what my original password was, but I've set a new one! I'll let you update the title to what you feel is appropriate. I think it's good to have the information here for other folk that might overlook the interrupt enable for various components (I've done it myself before too lol).

As to unclean projects, I have those in droves! I've actually been updating the neopixel library to support blink patterns and the likes so it's more suited to indicator LEDs such as SD Card read/write state and so fourth. I'll have to tidy the updated version up and get it uploaded, probably as a separate project on GitHub. The main addition that a user sees so far is a function for defining the desired blink patterns as a string like: "T5 R255 G0 B0 r0 g0 b0 ..._---_...__" which sets "dot" length to 5 frames, ON colour to R255G0B0, OFF colour to R0G0B0 and then blinks in an SOS pattern (..._---_...__). "." is 5-frames, "-" is 3xdot (15 frames) and "_" is a blank (3xdot). Not decided if this is actually useful to most people as it uses heap allocation (malloc and free), but it's exceptionally useful for the project I've been working on! It also has rudimentary support for neopixel rings allowing a pattern to be defined in a similar fashion to animate around the ring - this makes for an excellent beacon-control API ( http://www.thingiverse.com/thing:1183672/apps ). I think for your application, the basic library is probably more suitable : )

**Comment by PolyVinalDistillate** [comment]
I see my underscores in the above post have been interpreted as bold text! Damn you GitHub for trying to be clever!
![image](https://cloud.githubusercontent.com/assets/9323052/25998887/df974ed2-371a-11e7-91e0-142e10a32c42.png)
I'll try copy-pasting that image instead!

**Comment by akudoma** [comment]
Ha, I didn't realize that I was also replying to the thread address in the emails. I cleaned up the conversation to remove the replied to text.

Nick, the library sounds great, I am very interested in seeing it when you are ready to post!

Thanks again for the help. Hopefully my blunder is a good lesson to others about the global interrupt enable!
